project:
  type: website
  output-dir: docs

website:
  title: "Quantum Computing at the University of Tartu"
  navbar:
    left:
      - proandpre.qmd
      - kvantblog.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true



